---
jokes:
  - "¿Que le dice un pato a otro?\n Estamos empatados."
  - "¿Cual es la cantante favorita de los dinosaurios?\n Mayli Cyrus"
  - "¿Como se llama el dinosaurio que esta afonico?\n Roncosaurio"