---
jokes:
  - "¿Que le dice un pato a otro?\n Estamos empatados."
  - "¿Cual es la cantante favorita de los dinosaurios?\n Mayli Cyrus"
  - "¿Como se llama el dinosaurio que esta afonico?\n Roncosaurio"
  - "Este era un chiste tan malo, pero tan malo, que pegaba a todos los chistes más pequeños que él"
  - "¡Capitán, capitán! Están a punto de atacarnos 40 carabelas.\n ¿Una flota?\n No, flotan todas."
  - "Jaimito, puedes definir el término telepatía.\n Pues es una tele para la hermana de mi mamá."
  - "¿Sabes cómo se queda un mago después de comer?\n Magordito."
  - "Carlitos, puedes decirme una palabra que tenga muchas “o”.\n Muy fácil maestra,\n ¡Gooooooool!"
  - "¿Por qué las focas en el espectáculo siempre miran hacia arriba?\n Porque es donde se encuentran los focos."
  - "Buenas tardes, ¿me gustaría alquilar un “Batman Forever”?\n No es posible, tienes que devolverlo tomorrow."
  - "¿Qué le dice un techo a otro?\n Techo de menos."
  - "Donald usa teclado y Mickey mouse."
  - "Jaimito, ¿qué harías si te estuvieses ahogando en el mar?\n Pues llorar mucho para desahogarme."
  - "Un niño llama a la lavandería y pregunta: ¿ahí es donde lavan la ropa?\n No, le contestan del otro lado del teléfono.\n Pues que sucios sois."
  - "Hola, ¿está Agustín?\n No, estoy incomodín."
  - "¿Cómo sube Thor a un rascacielos?\n Pues en un ElevaThor."
  - "¿Por qué el volcán está considerado como la montaña más limpia?\n Porque echa cenizas y después lava."
  - "Mamá, ¿cómo se dice perro en inglés?\n Dog.\n Y veterinario.\n Pues Dog-tor."
  - "¿Cuál es la fruta más divertida?\n Sin duda, la naranjajajajaja"
  - "¿Qué le regaló Batman a su mamá por su cumpleaños?\n Una Bat-idora."
  - "Carlitos, ¿puedes decirme dos palabras que tengan tilde?\n Muy sencillo, maestra: Matilde y Clotilde."
  - "¡Profesora! Acaban de robarme en el pasillo.\n No me digas, ¿y qué te robaron, Jaimito?\n Pues los deberes."
  - "¿Qué le dice una iguana a su hermana gemela?\n Somos iguanitas."
  - "¡Me acaba de morder una serpiente!\n ¿Cobra?\n No, por suerte fue gratis."
  - "¿Cuál es el colmo de un futbolista?\n Que le hagan la pelota."
  - "Juanito, ve corriendo a la cocina que las lentejas se están pegando.\n Mamá, lo siento, pero me has enseñado a no meterme en peleas ajenas."
  - "¿Qué le dice un gusano a otro?\n Me voy a dar la vuelta a la manzana."
  - "¿Qué es un pez en un cine?\n Un mero espectador."
  - "¿Por qué se suicidó el libro de matemáticas?\n Porque tenía muchos problemas por resolver."
  - "¿Por qué a los esqueletos no les gusta la lluvia y el frío?\n Porque se calan hasta los huesos."
  - "Pepito, ¿por qué tu redacción sobre la leche te ha quedado tan corta?\n Porque hablo de la leche condensada maestra."
  - "Si los zombies se degradan con el paso del tiempo, entonces son ¿zombiodegradables?."
  - "Buenos días, ¿tienen libros sobre el cansancio?\n Sí, pero ahora mismo están todos agotados."
  - "Oye, ¿Como te llamas?\n Batman\n ¿Y tu donde haces popo?\n En el bat-er."
  - "¿Cuál es el vehículo favorito de un dinosaurio?\n El tractor-Saturio."
